doctrine:
    dbal:
        # TODO In case of special URL characters, this needs to be handled differently
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        # Defined in the compiler pass to use SchemaDefDriver
        # mappings:
        #     App:
        #         is_bundle: false
        #         type: staticphp
        #         dir: '%kernel.project_dir%/src/Entity'
        #         prefix: 'App\Entity'
        #         alias: App
