version: '3.3'

services:
  nginx:
    image: nginx:latest
    restart: always
    tty: false
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/gnusocial
      - ./nginx.conf:/etc/nginx/conf.d/gnusocial.conf

  php:
    build: docker/php
    restart: always
    tty: true
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/gnusocial

  postgres:
    image: postgres:alpine
    restart: always
    tty: false
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_DB=social
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
